<?php

namespace LostAndFoundBundle\Repository;

/**
 * LostAndFoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LostAndFoundRepository extends \Doctrine\ORM\EntityRepository
{
}
